# This is a basic workflow that is manually triggered

name: Tests
on : [push]
jobs:
  RunTest:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout code
      uses : actions/checkout@v4
    - run: echo 'Installation des requirements'
    - run: python -m pip install -r requirements.txt
    - run: 'Lancement des tests'
    - run: python -m unittest
